# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1057, 633)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1061, 711))
        self.label.setStyleSheet("background-color: #101010;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setEnabled(True)
        self.submitButton.setGeometry(QtCore.QRect(720, 480, 171, 51))
        self.submitButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.submitButton.setStyleSheet("background-color: 8ec9f9;\n"
"font-size: 15px;\n"
"color: rgb(169, 169, 169)\n"
"\n"
"")
        self.submitButton.setObjectName("submitButton")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(450, 100, 171, 21))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(-1)
        font.setBold(False)
        font.setUnderline(False)
        self.Title.setFont(font)
        self.Title.setStyleSheet("font-size: 28px")
        self.Title.setObjectName("Title")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 25, 1061, 51))
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.header = QtWidgets.QLabel(self.centralwidget)
        self.header.setGeometry(QtCore.QRect(20, 20, 58, 16))
        self.header.setStyleSheet("font-size: 15px;\n"
"")
        self.header.setObjectName("header")
        self.selectButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectButton.setGeometry(QtCore.QRect(250, 200, 131, 41))
        self.selectButton.setStyleSheet("background-color: none;\n"
"font-size: 14px;\n"
"color: rgb(169, 169, 169);")
        self.selectButton.setObjectName("selectButton")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(240, 430, 351, 20))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        font.setItalic(True)
        self.statusLabel.setFont(font)
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.folderPath = QtWidgets.QLabel(self.centralwidget)
        self.folderPath.setGeometry(QtCore.QRect(260, 250, 551, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.folderPath.setFont(font)
        self.folderPath.setStyleSheet("color: rgb(94, 94, 94)")
        self.folderPath.setText("")
        self.folderPath.setObjectName("folderPath")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.submitButton.setText(_translate("MainWindow", "submit"))
        self.Title.setText(_translate("MainWindow", "DICOM Form"))
        self.header.setText(_translate("MainWindow", "SNU-H"))
        self.selectButton.setText(_translate("MainWindow", "select folder"))
