# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1057, 633)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1061, 711))
        self.label.setStyleSheet("background-color: #101010;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setEnabled(True)
        self.submitButton.setGeometry(QtCore.QRect(730, 450, 101, 41))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(-1)
        self.submitButton.setFont(font)
        self.submitButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.submitButton.setStyleSheet("background-color: #101010;\n"
"font-size: 15px;\n"
"color: #91C9F8;\n"
"\n"
"")
        self.submitButton.setObjectName("submitButton")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(450, 100, 171, 21))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(-1)
        font.setBold(False)
        font.setUnderline(False)
        self.Title.setFont(font)
        self.Title.setStyleSheet("font-size: 28px;\n"
"color: white;")
        self.Title.setObjectName("Title")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 25, 1061, 51))
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.header = QtWidgets.QLabel(self.centralwidget)
        self.header.setGeometry(QtCore.QRect(20, 20, 58, 16))
        self.header.setStyleSheet("font-size: 15px;\n"
"color: white;\n"
"")
        self.header.setObjectName("header")
        self.selectButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectButton.setGeometry(QtCore.QRect(250, 200, 151, 41))
        self.selectButton.setStyleSheet("background-color: #101010;\n"
"font-size: 15px;\n"
"color: #91C9F8;")
        self.selectButton.setObjectName("selectButton")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(260, 410, 351, 20))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        font.setItalic(True)
        self.statusLabel.setFont(font)
        self.statusLabel.setStyleSheet("color: rgb(235, 235, 235);")
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.folderPath = QtWidgets.QLabel(self.centralwidget)
        self.folderPath.setGeometry(QtCore.QRect(410, 210, 511, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.folderPath.setFont(font)
        self.folderPath.setStyleSheet("color: rgb(235, 235, 235);")
        self.folderPath.setText("")
        self.folderPath.setObjectName("folderPath")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 250, 361, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(145, 145, 145);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 270, 461, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(145, 145, 145);")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.submitButton.setText(_translate("MainWindow", "SUBMIT"))
        self.Title.setText(_translate("MainWindow", "DICOM Form"))
        self.header.setText(_translate("MainWindow", "SNU-H"))
        self.selectButton.setText(_translate("MainWindow", "SELECT FOLDER"))
        self.label_2.setText(_translate("MainWindow", "※ Please select Raw DICOM Folder"))
        self.label_3.setText(_translate("MainWindow", "(DICOM folder name should be SUBJ_CTDATE: ex) KU39009_20220921)"))
