# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1057, 712)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1061, 691))
        self.label.setStyleSheet("background-color: #101010;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setEnabled(True)
        self.submitButton.setGeometry(QtCore.QRect(790, 530, 171, 51))
        self.submitButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.submitButton.setStyleSheet("background-color: 8ec9f9;\n"
"font-size: 14px;\n"
"color: #aea8a8;")
        self.submitButton.setObjectName("submitButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(450, 110, 151, 21))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font-size: 24px")
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 25, 1061, 51))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 58, 16))
        self.label_3.setStyleSheet("font-size: 15px;\n"
"")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 210, 191, 41))
        self.pushButton.setStyleSheet("bolder: 1px solid white;\n"
"background-color: none;\n"
"font-size: 14px;")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.submitButton.setText(_translate("MainWindow", "submit"))
        self.label_2.setText(_translate("MainWindow", "DICOM Form"))
        self.label_3.setText(_translate("MainWindow", "SNU-H"))
        self.pushButton.setText(_translate("MainWindow", "select folder"))
